# Generated by Django 3.2.3 on 2021-05-19 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qinaservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name': 'ambulance',
            },
        ),
        migrations.RenameModel(
            old_name='hs',
            new_name='hospital',
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'hospital'},
        ),
    ]
