# Generated by Django 3.2.3 on 2021-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qinaservices', '0003_auto_20210519_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='enname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='type',
            field=models.CharField(default='mm', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
