# Generated by Django 3.2.3 on 2021-09-22 10:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qinaservices', '0004_auto_20210922_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_a_field', models.CharField(max_length=150)),
                ('section_e_field', models.CharField(max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'CityBorder',
            },
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'Roads',
            },
        ),
        migrations.AddField(
            model_name='ambulance',
            name='carnum',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='enname',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firestation',
            name='enname',
            field=models.CharField(default='mm', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highsc',
            name='classes',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highsc',
            name='enname',
            field=models.CharField(default='d', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='classes',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='enname',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='enname',
            field=models.CharField(default='f', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postoffice',
            name='e_name',
            field=models.CharField(default='d', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postoffice',
            name='grade',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postoffice',
            name='postal_cod',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparatorysc',
            name='classes',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparatorysc',
            name='enname',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primarysc',
            name='classes',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primarysc',
            name='enname',
            field=models.CharField(default='d', max_length=50),
            preserve_default=False,
        ),
    ]
